# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/copilot-setup-steps.yml"
  pull_request:
    paths:
      - ".github/workflows/copilot-setup-steps.yml"

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    name: Copilot Setup Steps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install NuGet package dependencies
        run: dotnet restore Application/Ed-Fi-ODS-AdminApi.sln